components/enrichers/depsdev/README.md
components/enrichers/depsdev/kustomization.yaml
components/enrichers/depsdev/main.go
components/enrichers/depsdev/main_test.go
components/enrichers/depsdev/task.yaml
go.mod
go.sum

this pr improves the deps.dev enricher by adding [scorecard](https://github.com/ossf/scorecard) information to each field

Depsdev improvements

---

cmd/draconctl/pipelines/build.go
go.mod
go.sum
pkg/manifests/httpfileloader.go
pkg/pipelines/tektonV1Beta1.go
pkg/pipelines/tektonV1Beta1_test.go
vendor/modules.txt

Fix httpFileLoader to only return an error when a problem has occurred

---

cmd/draconctl/pipelines/build.go
pkg/pipelines/tektonV1Beta1.go

Instead of using the kustomization prefix + the base pipeline name + the kustomization suffix, the Generate method of the `TektonV1Beta1` backend is modified to only use the base pipeline and the suffix to make things simpler and more straightforward.

Use base pipeline name + suffix from kustomization for generated pipelines (Fixes #129)

---

cmd/draconctl/migrations/inspect.go

Stacked on top of https://github.com/ocurity/dracon/pull/155
In the last couple of days the migrations test have failed locally for no apparent reason, since no code related to them has changed, the dependency versions have not changed and neither have the migrations themselves. After a little bit of digging it looks like something in the ubuntu container is causing the 'OutOrStderr' function call in the migrations inspect command to return the stderr instead of stdout which in turn causes the jq check in the migrations bash script to get an empty input instead of the JSON doc which in turn causes it to fail immediately. Changing the 'OutOrStderr' to 'OutOrStdout' ensures that the code will always output to stdout as expected or whatever is the out stream.

Minor fix to prevent failures of database migrations tests

---

pkg/components/metadata.go
pkg/components/types.go
pkg/components/types_test.go
pkg/pipelines/tektonv1beta1.go
pkg/pipelines/tektonv1beta1_test.go

before deploying a pipeline we resolve all the components in two stages. first we resolve components that are in the local filesystem or that will be downloaded. then, in the 'Deploy' method of the orchestrator implementations we deploy unmanaged Tasks and check that all the managed Tasks are present in the cluster. we should have more checks that the unmanaged Tasks have been resolved correctly before trying to do anything with them.
Fixes #170

fix 170: add more checks for unresolved components

---

pkg/components/metadata.go
pkg/components/metadata_test.go
pkg/components/types.go
pkg/pipelines/tektonv1beta1_utils.go

Data structures containing fields of ComponentType or Orchestration type get marshaled as integers, because these enums are integers themselves. The problem is that a human reading these YAML/JSONs will have trouble parsing the values, unless they are well acquainted with the values of the codebase. In order to make them more human-readable, this commit adds methods to both enums that allow them to be marshaled as string values. The enums remain as integer enums because this allows to use the enum also an implicit ordering of components in the case of the ComponentType.
fixes #176

176: marshal ComponentType and OrchestrationType as string

---

docs/getting-started.md
pkg/components/package.go
pkg/components/package_test.go
pkg/components/testdata/producers/cdxgen/task.yaml
pkg/pipelines/tektonv1beta1.go
pkg/pipelines/tektonv1beta1_test.go
pkg/pipelines/tektonv1beta1_utils.go

Different versions of Tekton apply different validations to a Pipeline. If one uses more than version they will probably get a more complete list of errors for their pipelines. After using different versions of Tekton, I discovered that the `dracon_scan_*` parameters for the producer tasks are not set correctly.
This PR fixes two issues:
1. the `dracon_scan_*` parameters are set correctly
2. the code that adds anchors and the `dracon_scan_*` parameters is consolidated in one place and tests are added to make sure that the Tasks are processed before being packaged in a Helm package or before getting deployed on the fly by the orchestrator.
fixes #180

Ensure dracon_scan_* variables are set correctly

---

Makefile

commit 1f104b0f fixes a typo in the component_binaries variable, however it didn't fix other instance of this variable used as dependencies, thus breaking the container publishing functionality. this commit fixes this.
Fixes #188

188: fix typo in make variable

---

deploy/dracon/chart/templates/kb-ingress.yaml
deploy/dracon/chart/values.yaml
deploy/dracon/values/dev.yaml

also removes a superfluous boolean controlling if Tekton gets deployed
Closes #195

195: allow user to choose if they want a Kibana ingress to be deployed

---

Makefile

current linter setup is very noisy, also reviewdog's github integraton has a bug that double/tripple reports findings on removed code, however, when running locally, the linter works as expected, so we do the same for ci/cd
closes #198

Fix linter noise

---

Makefile

the lint Make target will output in stderr all the issues that reviewdog discovered for the diff under investigation, however that stderr is not captured by the Github action. we need to send the stderr to stdout so that we can see it in the Github action logs when the lint action fails.

redirect reviewdog stderr to stdout

---

components/producers/golang-gosec/main.go
components/producers/kics/main.go
components/producers/python-bandit/main.go
components/producers/semgrep/main.go
components/producers/terraform-tfsec/main.go
components/producers/typescript-eslint/main.go

This PR fixes an issue where some producers failed if they were unable to extract the code for an `Issue`.
Instead, we now keep that field empty, and log a warning instead.

🐛 Fix some producers failing if unable to extract code

---

package-lock.json

This PR fixes an NPM audit alert by just running `npm audit fix`:

:wrench: bump node modules

---

.github/workflows/publish.yml

this will allow anyone building on top of the `draconctl` image for their migrations to just use the latest tag instead of having to hard code the version of the base image
Closes #225

225: push the draconctl image also with the latest tag

---

components/producers/semgrep/README.md
components/producers/semgrep/task.yaml

This PR adds a new parameter `producer-semgrep-config-value` to the `producer/semgrep`. By default, it's set to `auto`.
Adding this new parameter makes the SemGrep producer immediately useful, without needing to define custom rules in YAML.
The binary also supports multiple `--config` parameters, so the two parameters don't interfere with each other.

[OCU-113] 🐛 Fix `producer/semgrep` not supporting registry

---

components/enrichers/policy/README.md
examples/pipelines/cdxgen-project/kustomization.yaml
examples/pipelines/dast-project/kustomization.yaml
examples/pipelines/golang-project/kustomization.yaml
examples/pipelines/iac-project/kustomization.yaml
examples/pipelines/java-project/kustomization.yaml
examples/pipelines/misc-project/kustomization.yaml
examples/pipelines/nancy-purl-project/kustomization.yaml
examples/pipelines/python-project/kustomization.yaml
examples/pipelines/typescript-project/kustomization.yaml

This PR removes the `enrichers/policy` from the example pipelines.
Removing this because it requires 5GB of memory to run, but
Docker Desktop by default only assigns 2GB to itself. The
component can still be run, but requires users to manually
tweak their memory limit. We decided this is too complex for
an example pipeline and would cause more harm than good.
Also [added a warning to enrichers/policy:README about these memory requirements](https://github.com/ocurity/dracon/commit/ca533cd86b19648d372a727c7261e699c4e23dd6).

Remove policy enricher from example pipelines

---

.github/workflows/publish.yml

You can see the error over here: https://github.com/ocurity/dracon/actions/runs/9976308431/job/27568157322

fix for GH publish action Helm package path

---

components/enrichers/aggregator/main_test.go
components/enrichers/codeowners/main.go
components/enrichers/codeowners/main_test.go
components/enrichers/deduplication/main_test.go
components/enrichers/depsdev/main.go
components/enrichers/depsdev/main_test.go
components/enrichers/depsdev/types/types.go
components/enrichers/enricher.go
components/enrichers/enricher_test.go
components/enrichers/policy/main_test.go
components/enrichers/test_utils.go
components/producers/producer_test.go

Via OCU-104 we discovered that the `enricher-aggregator` component crashes if no issues were enriched. This is a bug. It shouldn't crash, it should simply produce an aggregated output with no findings.
In this PR, we ensure all existing enricher components always produce a result. If there were no issues supplied to the respective enrichers we simply store an empty list result.
We also add tests for this behaviour to all enrichers.

[OCU-104] Ensure Enrichers Always Produce an Output

---

Makefile
components/consumers/elasticsearch/task.yaml
components/consumers/mongodb/task.yaml
components/enrichers/codeowners/main.go
components/enrichers/codeowners/main_test.go
components/enrichers/deduplication/main.go
components/enrichers/deduplication/main_test.go
components/enrichers/depsdev/main.go
components/enrichers/policy/main.go
components/enrichers/policy/main_test.go
components/producers/semgrep/task.yaml
components/producers/typescript-eslint/task.yaml
components/producers/typescript-yarn-audit/main.go
components/producers/typescript-yarn-audit/task.yaml
components/producers/typescript-yarn-audit/types/yarn-issue.go
components/producers/typescript-yarn-audit/types/yarn-issue_test.go
examples/pipelines/golang-project/kustomization.yaml
examples/pipelines/golang-project/pipelinerun.yaml
examples/pipelines/python-project/kustomization.yaml
examples/pipelines/python-project/pipelinerun.yaml
examples/pipelines/typescript-project/kustomization.yaml
examples/pipelines/typescript-project/pipelinerun.yaml
pkg/components/package_test.go

This PR fixes three existing example workflows, so they run successfully and produce valid results.
We now have three example pipelines (golang, typescript, python) that all produce useful results. To achieve this, several things were changed.
- 🔧 Change default ES and MongoDB URLs: They were referencing nonexistent instances
- 🔧 Replace enricher-deduplication with enricher-codeowners: De-duplication is broken atm, Spyros is working on a fix
- 🔧 Change example golang pipeline: Referenced a few params that aren't needed
- 🔧 Change example python pipeline: Also referenced a few params that aren't needed
- 🐛 Fix incorrect parameter name in TS example pipeline: Was referencing a nonexistent parameter
- 🐛 Fix producer/yarn-audit not handling empty lines: The input file is a very weird JSON, …

[OCU-155] Fix example workflows are failing

---

components/producers/python-bandit/main.go
components/producers/python-bandit/main_test.go
components/producers/semgrep/main.go
components/producers/semgrep/main_test.go
components/producers/semgrep/types/semgrep-issue.go
components/producers/semgrep/types/semgrep-issue_test.go

Both the Semgrep and Bandit producers were not correctly propagating the CWE from their JSON inputs. This is now fixed.

[OCU-118] 🐛 Fix Semgrep and Bandit producers not recording CWE

---

components/consumers/slack/Dockerfile
components/consumers/slack/Makefile
components/consumers/slack/task.yaml

This PR fixes the Slack consumer. It previously failed to make requests to the Slack API.
Running the Slack consumer as part of a pipeline, it failed with the below error message:
> could not push metrics: Post \"[https://hooks.slack.com/services/XXX/XXX/XXX\](https://hooks.slack.com/services/XXX/XXX/XXX/)": tls: failed to verify certificate: x509: **certificate signed by unknown authority**
This is because the default docker image uses `scratch` as it's base, which doesn't come with CAs.
We are resolving that by instead using an `alpine` image as the base, with added `ca-certificates`.

Fix Slack Consumer

---

.github/workflows/format.yml
.github/workflows/lint.yml
.github/workflows/test.yml
Makefile

This PR improves the golang test runner, both in CI but also locally. In particular, it does these three things to achieve that:
Previously our test output was only in JSON - easy to read for a machine, harder to read for a human.
The `gotestsum` package is a drop-in replacement for `go test` and [very widely used](https://github.com/gotestyourself/gotestsum?tab=readme-ov-file#who-uses-gotestsum) (e.g. by kubernetes).
Three main improvements it brings are:
1. Change the [test output format](https://github.com/gotestyourself/gotestsum?tab=readme-ov-file#output-format), from compact to verbose with color highlighting.
2. Print a [summary](https://github.com/gotestyourself/gotestsum?tab=readme-ov-file#summary) of the test run after running all the tests.
3. write a JUnit XML file for …

Improve Go Test Runner

---

components/producers/docker-trivy/task.yaml
components/producers/producer.go
examples/pipelines/sca-project/kustomization.yaml
examples/pipelines/sca-project/pipelinerun.yaml

The component previously didn't run. Now it does.
Also adding an example workflow for a SCA usecase.

Fix `producers/docker-trivy` Component

---

Makefile
components/enrichers/deduplication/task.yaml
deploy/deduplication-db-migrations/chart/templates/migrations-job.yaml
deploy/deduplication-db-migrations/chart/values.yaml
deploy/deduplication-db-migrations/values/dev.yaml
deploy/dracon/chart/Chart.lock
deploy/dracon/values/dev.yaml

This PR introduces two new ways of installing dracon
` make dev-deploy ` will build everything and deploy it to the local cluster
` make install` will download the latest version of every package and install it to the local cluster
both commands first setup the local cluster in an idempotent way

make oss migrations run as part of dev-dracon

---

Makefile

The `make dev-deploy` script was previously broken, because it incorrectly included an `ocurity/dracon` prefix.
While the script itself didn't error, running any workflow would fail, as the images couldn't be found.
Removing this prefix resolves the issue.
Tested locally on a clean install via:
```bash
make dev-teardown
./scripts/kind-with-registry.sh
make dev-deploy
make cmd/draconctl/bin
bin/cmd/draconctl pipelines deploy ./examples/pipelines/golang-project
kubectl create \
-n dracon \
-f ./examples/pipelines/golang-project/pipelinerun.yaml
```

🐛 Fix broken `make dev-deploy` script

---

Makefile

In particular:
- fix missing reference to `dev-infra` target
- fix incorrect passing of `CONTAINER_REPO`

🐛 Fix bug in `make install` target

---

.github/workflows/integration_test.yaml

This PR adds an E2E integration test to the GitHub Actions.
The test only gets executed on PRs to the `main` branch. It attempts to install dracon using the `make dev-deploy` command. Then, it deploys the Golang example pipeline and waits for it to complete successfully. There is a maximum timeout of five minutes for the pipeline to succeed.

👷 Add E2E Integration Test to GitHub Actions

---

cmd/draconctl/main.go
cmd/draconctl/migrations/apply.go
cmd/draconctl/migrations/inspect.go
cmd/draconctl/migrations/revert.go
deploy/deduplication-db-migrations/chart/templates/migrations-job.yaml
pkg/db/migrations.go
tests/migrations/compose.yaml

Add error checking and logging to migrations

---

deploy/deduplication-db-migrations/chart/templates/_helpers.tpl

fix reference to image.repository in deduplication migrations reference to not include deduplication_db_migrations dictionary

---

components/consumers/dependency-track/main.go
components/consumers/dependency-track/main_test.go
components/consumers/dependency-track/task.yaml

Make dependency track consumer work with large boms and with proper flags

---

deploy/dracon/chart/values.yaml
deploy/dracon/values/dev.yaml

closes #341 
A change in the last two weeks has removed the postgresql password. As a result postgres generates its own and thus no migrations or components can be run

fix-bug-341-postgreql-does-not-have-credentials

---

components/consumers/elasticsearch/main.go

closes #379 
adds logs such as:
```{"time":"2024-09-26T11:57:01.590757103Z","level":"ERROR","msg":"could not contact remote Elasti
csearch: ","scanID":"","error":"could not contact Elasticsearch, attempted to retrieve cluster 
info and got status code: 401 as a result, body: [401 Unauthorized] {\"error\":{\"root_cause\":
[{\"type\":\"security_exception\",\"reason\":\"unable to authenticate with provided credentials
and anonymous access is not allowed for this request\",\"additional_unsuccessful_credentials\"
:\"API key: unable to find apikey with id kkttHpIBE8LvqBqM9yuN\",\"header\":{\"WWW-Authenticate
\":[\"Basic realm=\\\"security\\\", charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\
"ApiKey\"]}}],\"type\":\"security_exception\",\"reason\":\"unable to authenticate with …
```

fix #379, add significantly more error logging

---

components/consumers/jira/task.yaml
components/consumers/jira/utils/utils.go
components/enrichers/custom-annotation/main.go
examples/pipelines/jira-project/kustomization.yaml
examples/pipelines/jira-project/pipelinerun.yaml
pkg/jira/config.yaml
pkg/jira/config/config_test.go
pkg/jira/config/types.go
pkg/jira/jira/api.go
pkg/jira/jira/api_test.go
pkg/jira/jira/apiutils.go
pkg/jira/jira/apiutils_test.go
pkg/jira/jira/issueTemplate.txt
pkg/templating/template_description.go

remove addToDescription, instead offer a default template
now the only piece of jira config needed to run the consumer is the project name

close #409, refactor Jira consumer,

---

scripts/cleanup_stdout_json_consumer_out.sh

Cleans up sample json output into a valid json format that makes sense.

Adding script to cleanup sample output from json consumer

---

Makefile
buf.gen.yaml
containers/Dockerfile.buf

Preparing for OSS work by generating Go types from [OSCF proto schema definition](https://github.com/ocsf/examples/tree/main/encodings/protobuf/proto).
Note: 
`buf` supports [git](https://buf.build//docs/reference/inputs#git) sources but funnily enough doesn't allow us to specify a destination for the generated code (like it usually happens for local development). Since buf relies on git for this remote generation, I added a bunch of stuff to the scratch image to allow so (I'm open to just use the base alpine image to simplify things if you think that it's tricky to understand).
---
>Why remote generation and not just copying over the type?
In this way we don't need to sync up manually and we can also target specific versions.
>Is there a buf schema registry for ocsf?
Nope …

Generating OCSF Go types from Proto Schema.

---

.gitattributes

Testing a GitHub customisation to flag generated code and do not expand changes to it on PR Diffs. This is a small QOL improvement for DevEx.
More info here https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github

Do not expand vendor/ changes on PR Diffs.

---

deploy/smithy/chart/values.yaml
deploy/smithy/values/dev.yaml
deploy/tektoncd/pipeline/templates/customresourcedefinitions.yaml
docs/getting-started.md
examples/pipelines/dast-project/kustomization.yaml
examples/pipelines/golang-project/kustomization.yaml
examples/pipelines/iac-project/kustomization.yaml
examples/pipelines/java-project/kustomization.yaml
examples/pipelines/misc-project/kustomization.yaml
examples/pipelines/nancy-purl-project/kustomization.yaml
examples/pipelines/python-project/kustomization.yaml
examples/pipelines/rails-project/kustomization.yaml
examples/pipelines/sca-project/kustomization.yaml
examples/pipelines/typescript-project/kustomization.yaml
examples/pipelines/yarn-audit-purl-project/kustomization.yaml

- [Removing Mongo until it runs better locally on Apple Chips without hacks](https://github.com/bitnami/containers/issues/53407)
- Replacing ES consumer with JSON consumer in sample go pipeline so everything works end to end
Tested and now requires 0 tweaks to work fine.

Disable MongoDB locally and Improve local golang pipeline example

---

components/consumers/pdf/README.md
components/consumers/pdf/default.html
components/consumers/pdf/example_data/gosec.enriched.aggregated.pb
components/consumers/pdf/main.go
components/consumers/pdf/main_test.go

[Ticket](https://linear.app/smithy/issue/OCU-261/pdf-consumer-default-report-needs-styling)
This PR adds styles and a bit of logic to the PDF consumer.
- fix missing HTML file result
- calculate total and high priority findings
- summarise findings in a list with links to details
- hide empty vulnerability rows
- colour coding per priority
- parse dates and display them in a human format
- added link to CWE
- added test data into the folder
- add "seen before" to summary table at the top
[report.pdf](https://github.com/user-attachments/files/17720495/report.pdf)

Feature: PDF consumer format

---

.reviewdog.yml
Makefile

in order to test this run locally: `make install-lint-tools list`

fix revive scanning command in reviewdog since it doesn't handle monorepos well

---

components/producers/snyk-node/task.yaml

our current snyk node component can only be used for repositories where the root folder is the one containing the NodeJS code, however it can't be used if the folder structure is any different or if there are multiple subfolder containing NodeJS projects.
this PR fixes this by allowing the user to define multiple paths to be scanned, and uses a better algorithm for deciding which package manager to use to resolve their dependencies. it stores the findings in a way that the parser can use to make sure that it has the full context about where they were discovered

allow snyk node to be used for monorepos

---

smithyctl/internal/images/component.go
smithyctl/internal/images/component_test.go

eg, if a component in `components/scanners/bla` has a helper image it can declare it in the `components/scanners/bla/helper` directory and the builder will build it using the same algorithm as when building a normal component image, meaning it will check if there is a Makefile with an `image` target, otherwise it will use a base Dockerfile for it.

fixes ocu-503: allow helper images to be built for a component

---

pkg/types/v1/parameter.go
sdk/component/store/remote/findings-client/README.md
sdk/component/store/remote/findings-client/client.go

The first bit fixes an issue that we have with parsing components across the codebases.
The second bit helps us with avoiding issues when running the remote sidecar.

Fix components serialisation/deserialisation + adding ability for gRPC remote client to retry

---

pkg/files/localfileloader.go

The `filepath` package is more OS-agnostic, allowing the local file loader to work on Windows.

Use `filepath` over `path` for path joining and comparison on `localFileLoader`

---

Makefile

Since we moved main into the root of `smithyctl` we need to update this target

Fixing target for building smithyctl.

---

.github/workflows/package-component.yaml

Uses [repository-dispatch](https://github.com/peter-evans/repository-dispatch) to trigger a "repackaging" action in SAAS after publishing a component package.
SAAS is already configured to handle this:
```yaml
...
on:
repository_dispatch:
types: [package_published]
...
jobs:
package:
runs-on: ubuntu-latest
steps:
- name: Process new package
id: process_new_package
run: |
REPO_NAME=${{ github.event.client_payload.repo_name }}
COMPONENT_TAG=${{ github.event.client_payload.component_tag }}
```

Trigger repackaging after packaging components.

---

sdk/component/enricher.go
sdk/component/enricher_test.go
sdk/component/filter.go
sdk/component/filter_test.go
sdk/component/reporter.go
sdk/component/reporter_test.go
sdk/component/scanner.go
sdk/component/scanner_test.go
sdk/component/store/remote/findings-client/client.go

- Skip running component steps when no findings are found for: enrichers, filters and reporters.
- Also avoid persisting findings during scanning if non are found.
- Return no findings found error also in the gRPC client as we do in the other storages

Enrichers, Filters and Reporters shouldn't error when no findings were found

---

new-components/Dockerfile
new-components/targets/git-clone/Makefile
new-components/targets/git-clone/dockerfiles/git-clone/Dockerfile
sdk/version.go
smithyctl/README.md
smithyctl/command/component/build.go
smithyctl/docs/component/BUILD.md
smithyctl/internal/images/component.go
smithyctl/internal/images/docker/builder.go
smithyctl/internal/images/docker/builder_test.go
smithyctl/internal/images/docker/testdata/Dockerfile

- Make SDK version customisable at compile time
- Support `sdk-version` flag on `smithyctl build`
- Injecting the flag into go build flags for base images

Track sdk version

---

components/targets/git-clone/component.yaml
components/targets/git-clone/internal/target/target.go
components/targets/git-clone/pkg/git/conf.go
components/targets/git-clone/pkg/git/git.go

Fixes an issue when cloning from a pull request ref https://plexor.saas.smithy.security/runs/68466b18-36b8-44e0-9fc2-e840d34b82cd.
Reverts some changes to the clone and does more heavy lifting in the Diff getter business logic where we try to resolve against an optional Base Reference or try out best with main/master.
If the reference is a base branch, the diff is skipped.

Bug not handling prs refs

---

components/reporters/discord/internal/reporter/issue.go
components/reporters/discord/internal/reporter/testdata/expected_msg1.txt
components/reporters/discord/internal/reporter/testdata/expected_msg2.txt
components/reporters/discord/internal/reporter/testdata/expected_msg3.txt
components/reporters/jira/internal/reporter/reporter.go
components/reporters/jira/internal/reporter/testdata/expected_issue1.txt
components/reporters/jira/internal/reporter/testdata/expected_issue2.txt
components/reporters/jira/internal/reporter/testdata/expected_issue3.txt

We were linking to out of date `/instances`.

Link correctly to runs

---

components/reporters/linear/component.yaml
components/reporters/linear/internal/config/config.go

Fixes `unexpected error: failed to create linear client: invalid config: invalid empty base url`

Add missing LINEAR_BASE_URL env var to conf and also handle the default.

---

components/enrichers/reachability/cdxgen-atom-runner/Dockerfile
components/scanners/codeql/codeql-image/Dockerfile

Fixes codeql and cdxgen build errors when packaging.

Bump go to 1.24 in custom Dockerfiles.

---

sdk/python/smithy/components/enricher.py

and pushes the logger to the component(parent class) regardless if the logger is none or not.

fix: this fixxes a bug where the enricher does not check the logger

---

smithyctl/command/component/package.go
smithyctl/docs/component/PACKAGING.md

I think that this is a regression that came out when we extended smithyctl's package capabilities.
This fixes an issue where [server gave HTTP response to HTTPS client](https://stackoverflow.com/questions/49674004/docker-repository-server-gave-http-response-to-https-client) when auth is disabled on packaging.
To test it, you can run:
- `make cmd/smithyctl`
- Spin up https://hub.docker.com/_/registry on port 5000
- `bin/../smithyctl component package --registry-url=127.0.0.1:5000 --sdk-version=v1.0.0 --version=v1.0.0 --registry-auth-enabled=false --registry-plain-http=true components/reporters/json-logger/component.yaml`

Configure Smithyctl's docker client's UsePlainHTTP based on --auth-enabled=true flag

---

.github/workflows/package-component.yaml
.github/workflows/test-go.yml
Makefile
go.mod
sdk/go.mod
smithyctl/go.mod

this PR does a bunch of small fixes left and right:
* fixes our use of caching for the Go tests. building all the binaries for the various components is a CPU intensive job and without all the intermediate artefacts it does take quite some time. if the dependencies are cached this is reduced quite a bit. this run had no caching and it took 22m: https://github.com/smithy-security/smithy/actions/runs/17298936728/job/49104467418 while this one used caching and it took less than 1m: https://github.com/smithy-security/smithy/actions/runs/17299619005/job/49106895430?pr=1076
* adds some phony targets that were missing
* adds a couple of missing docstrings from Makefile

fix go versions and action caching

---

components/scanners/osv-scanner/component.yaml
components/scanners/osv-scanner/go.mod
components/scanners/osv-scanner/go.sum
components/scanners/osv-scanner/internal/transformer/testdata/osv-scan-mismatch-path.sarif.json
components/scanners/osv-scanner/internal/transformer/testdata/osv-scan-single-output.sarif.json
components/scanners/osv-scanner/internal/transformer/transformer.go
components/scanners/osv-scanner/internal/transformer/transformer_test.go
components/scanners/osv-scanner/vendor/github.com/smithy-security/pkg/sarif/sarif.go
components/scanners/osv-scanner/vendor/modules.txt

Output from the json logger, using smithyctl locally
```
{"time":"2025-09-16T15:40:33.822795463Z","level":"INFO","msg":"found finding","sdk_version":"unset","instance_id":"8b414898-0997-49a7-bc1b-0994fdbb7881","component_name":"json-logger","component_type":"reporter","num_findings":35,"finding":"{\"activityId\":\"ACTIVITY_ID_CREATE\",\"activityName\":\"ACTIVITY_ID_CREATE\",\"categoryName\":\"CATEGORY_UID_FINDINGS\",\"categoryUid\":\"CATEGORY_UID_FINDINGS\",\"className\":\"CLASS_UID_VULNERABILITY_FINDING\",\"classUid\":\"CLASS_UID_VULNERABILITY_FINDING\",\"confidence\":\"CONFIDENCE_ID_UNKNOWN\",\"confidenceId\":\"CONFIDENCE_ID_UNKNOWN\",\"count\":1,\"findingInfo\":{\"createdTime\":\"1758037233\",\"createdTimeDt\":\"2025-09-16T15:40:33.631788755Z\",\"dataSources\":[\"{\\\"targetType\\\":\\\ …
```

Update osv-scanner to use the new sarif package
